# Generated by Django 4.2.1 on 2023-05-29 17:19

from django.db import migrations, models
import django.db.models.deletion
import ventas.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('codCargo', models.IntegerField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=50)),
                ('fCreacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'harrys_cargo',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=20, unique=True, verbose_name='Color')),
                ('rgb', models.CharField(max_length=10, verbose_name='Paleta_RGB')),
                ('hex', models.CharField(max_length=10, verbose_name='Paleta_Hex')),
            ],
            options={
                'db_table': 'harrys_color',
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('idComuna', models.IntegerField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('fCreacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'harrys_comuna',
            },
        ),
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('codFormaPago', models.IntegerField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'harrys_formapago',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('idGenero', models.AutoField(db_column='id_genero', primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10)),
                ('genero', models.CharField(max_length=20)),
                ('fCreacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'harrys_genero',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('rut', models.IntegerField(primary_key=True, serialize=False)),
                ('dv', models.CharField(max_length=1)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('papellido', models.CharField(blank=True, max_length=30, null=True)),
                ('sapellido', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('fechaNacimiento', models.DateField(auto_now_add=True, db_column='fecha_nacimiento', null=True)),
                ('activo', models.IntegerField(blank=True, null=True)),
                ('fCreacion', models.DateTimeField(auto_now_add=True)),
                ('comuna', models.ForeignKey(db_column='id_comuna', on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.comuna')),
                ('genero', models.ForeignKey(db_column='id_genero', on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.genero')),
            ],
            options={
                'db_table': 'harrys_persona',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('idRegion', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('fCreacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'harrys_region',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.OneToOneField(db_column='rut', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ventas.persona')),
                ('foto', models.ImageField(null=True, upload_to=ventas.models.cargarFoto)),
                ('fCreacion', models.DateTimeField(auto_now_add=True)),
                ('credito', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'harrys_cliente',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=20, unique=True)),
                ('clave', models.CharField(max_length=10)),
                ('rut', models.ForeignKey(db_column='rut', on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.persona')),
            ],
            options={
                'db_table': 'harrys_usuario',
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('idSucursal', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('direccion', models.TextField(default=0)),
                ('fCreacion', models.DateTimeField(auto_now_add=True)),
                ('idComuna', models.ForeignKey(db_column='id_comuna', default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.comuna')),
            ],
            options={
                'db_table': 'harrys_sucursal',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('idProvincia', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('fCreacion', models.DateTimeField(auto_now_add=True)),
                ('region', models.ForeignKey(db_column='id_region', on_delete=django.db.models.deletion.CASCADE, to='ventas.region')),
            ],
            options={
                'db_table': 'harrys_provincia',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('idEmpleado', models.AutoField(primary_key=True, serialize=False)),
                ('sueldo', models.IntegerField()),
                ('fCreacion', models.DateTimeField(auto_now_add=True)),
                ('codCargo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.cargo')),
                ('idGenero', models.ForeignKey(db_column='id_genero', on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.genero')),
                ('rut', models.ForeignKey(db_column='rut', on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.persona')),
            ],
            options={
                'db_table': 'harrys_empleado',
            },
        ),
        migrations.AddField(
            model_name='comuna',
            name='provincia',
            field=models.ForeignKey(db_column='id_provincia', on_delete=django.db.models.deletion.CASCADE, to='ventas.provincia'),
        ),
    ]
